# Generated by Django 6.0.1 on 2026-03-02 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0002_offer_shipping_fee_offer_total_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='shipping_fee',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='total_price',
        ),
    ]
