# Generated by Django 6.0.1 on 2026-03-03 14:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComparisonSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=255)),
                ('location', models.CharField(default='outside beirut', max_length=50)),
                ('min_price', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('sites_checked', models.IntegerField(default=0)),
                ('sites_succeeded', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comparison_searches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ComparisonResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=50)),
                ('product_title', models.CharField(max_length=500)),
                ('product_url', models.URLField(max_length=1000)),
                ('image_url', models.URLField(blank=True, max_length=1200, null=True)),
                ('in_stock', models.BooleanField(null=True)),
                ('item_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('shipping_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('tax_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('delivery_time', models.CharField(blank=True, max_length=100, null=True)),
                ('delivery_days', models.IntegerField(blank=True, null=True)),
                ('store_rating', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('score', models.DecimalField(decimal_places=1, max_digits=4)),
                ('price_score', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('delivery_score', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('trust_score', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('pricing_breakdown', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('search', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='comparisons.comparisonsearch')),
            ],
            options={
                'ordering': ['-score'],
            },
        ),
        migrations.AddIndex(
            model_name='comparisonsearch',
            index=models.Index(fields=['-created_at'], name='comparisons_created_7ca223_idx'),
        ),
        migrations.AddIndex(
            model_name='comparisonsearch',
            index=models.Index(fields=['user', '-created_at'], name='comparisons_user_id_eb3b4c_idx'),
        ),
        migrations.AddIndex(
            model_name='comparisonresult',
            index=models.Index(fields=['search', '-score'], name='comparisons_search__b052b3_idx'),
        ),
    ]
